version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    tty: true
    stdin_open: true
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
volumes:
  dbdata:
